### ISSUE TITLE
Laptop script.

### ISSUE THREAD

**Issue by macemalakai** [monfresh/laptop#1]
Everything went smooth with the laptop script until the very end. Any ideas?

Updating bundler ...
Updating installed gems
Nothing to update

Configuring Bundler ...
mac: line 174: bundle: command not found
failed

**Comment by monfresh** [comment]
Thanks for the report. Could you please copy and paste (or attach) your `~/laptop.log`?

Also, what version of OS X are you using?

**Comment by ksprashu** [comment]
I faced the same thing.

The first time it kept asking for some passwords and the script failed at some point (probably due to wrong passwords)

The next time I ran it, it would skip through everything and then finally fail at the step gem_install_or_upgrade 'bundler'

Since I ran it the second time, I lost the original log.

As a solution, I ran manually $ gem install bundler and then re-ran the mac script. Now it seems to continue and do something.

However, can I uninstall everything this script did (easily?) and / or force it to do everything again so that nothing is missed out?

**Comment by monfresh** [comment]
@ksprashu The script is safe to run multiple times. I run it about once a week as a quick way to upgrade everything to the latest version. If something is missing, it will install it when you run the script. There's no need to uninstall anything.

@macemalakai Can you try quitting and relaunch Terminal to see if it fixes your issue? If not, can you please run these commands and let me know what they output:
```
rvm type | head -1
```
```
rvm -v
```
```
ruby -v
```

**Comment by monfresh** [comment]
So, I figured it out the issue by testing this on a clean installation of Yosemite. It turns out this is due to a change in the output of `gem list bundler --installed`. If `bundler` is not installed, it now returns `false` whereas before it presumably didn't return anything, so the [gem_install_or_update](https://github.com/monfresh/laptop/blob/master/mac#L87-95) function thinks that bundler is installed and tries to update it instead of installing it.

I will fix this today.

**Comment by monfresh** [comment]
The actual reason for this issue is explained in #2. It is fixed now.
