### ISSUE TITLE
Laptop Script Issue

### ISSUE THREAD

**Issue by Lstan01** [monfresh/laptop#15]
I'm having trouble finishing the laptop script for installing developer tools. It tells me github is already installed but stops after it tells me the app does not exist. I couldn't find github in my downloads either.

I appreciate any help. If you need to see more text from terminal let me know, thanks.

Updating bundler ...
Updating installed gems
Nothing to update

Configuring Bundler ...
Your application has set jobs to "1". This will override the global value you are currently setting

Already using the latest version of heroku-toolbelt. Skipping ...

Already using the latest version of brew-cask. Skipping ...

flux is already installed. Skipping...

github is already installed. Skipping...

sublime-text3 is already installed. Skipping...
The file /Users/loganstanley/Applications/GitHub.app does not exist.
failed

LoganStnleysMBP:~ loganstanley$

**Comment by monfresh** [comment]
Thanks for the report. The script actually completed all the essentials. This last error message is due to a bug that I will fix in a few minutes. The last thing the script tries to do is launch the GitHub app if it thinks you haven't set your SSH keys yet, but the way it determines whether or not to launch GitHub is flawed.

In your case, you do have GitHub app installed. It should be in your `/Applications` folder, the same place where most of your OS X apps are. You should be able to launch it via Spotlight.

**Comment by monfresh** [comment]
Fixed in #16.
