### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by SamHep0803** [monfresh/laptop#46]
I'm sure this is probably one of the easiest fixes but is there a way to uninstall the package.

Again I'm sure this is one of the easiest fixes but I just want to uninstall.

Thanks for any help.

**Comment by SamHep0803** [comment]
Also I've only just noticed this but my whole desktop has been wiped out and deleted...

I don't know what happened

**Comment by monfresh** [comment]
HI @SamHep0803. This script does not do anything with the Desktop. I'm not sure what you mean by "my whole desktop has been wiped out and deleted..."

As for uninstalling, there isn't an uninstaller yet. This script is not a single package that you install. It installs a lot of different things, as documented here: https://github.com/monfresh/laptop#what-it-sets-up

The good news is that most of the things are installed by Homebrew, so if you uninstall Homebrew, it should uninstall most everything else. Follow these instructions to uninstall Homebrew: https://github.com/Homebrew/install#uninstall-homebrew

Next, you'll need to remove the following apps from your `/Applications` folder (assuming you don't want them):

Flux
GitHub Desktop
Sublime Text

You will then need to remove any lines that you didn't add yourself from the following files:

~/.bash_profile
~/.zshrc

**Comment by SamHep0803** [comment]
Thanks @monfresh What I mean by my desktop has been wiped out and deleted is all the files that I had on my Desktop has been either deleted or they are hidden.

I don't really know.

**Comment by SamHep0803** [comment]
One More thing are there any specific lines I need to delete in ~/.bash_profile and ~/.zshrc or do I just delete every thing?

Many Thanks Sam

**Comment by monfresh** [comment]
It depends. If you haven't touched those files before running my script, or if you haven't run any apps or other scripts that might have touched those files, then you can delete everything. If you're not sure, then to see which lines my script added, do a search for `append_to_file "$shell_file"` in this file: https://github.com/monfresh/laptop/blob/master/mac

For example, on line 136, you will see that it adds the line `export PATH="$HOME/.bin:$PATH"`:
https://github.com/monfresh/laptop/blob/master/mac#L136

However, note that if that line already existed in your file, then even though it looks like my script tries to add it, it won't add it because it was already there. So, it's hard to tell for sure whether or not you should remove any lines you might need. It all depends on what you did before running my script.

Does that make sense?

**Comment by Zheng7426** [comment]
Hey mate, 

How can I uninstall the styling change of my terminal?

Thanks.

**Comment by monfresh** [comment]
@Zheng7426 Hi. You can remove these lines from your `.bash_profile` or `.zshrc` files, which you can find in your "home" folder:

export PS1="${ORANGE}[\w] ${GREEN}$(prompt_ruby_info) ${NORMAL}$ "
precmd () { PS1="${ORANGE}[%~] ${GREEN}$(prompt_ruby_info) ${NORMAL}$ " }
export CLICOLOR=1;
export LSCOLORS=exfxcxdxbxegedabagacad;

**Comment by Zheng7426** [comment]
@monfresh Thank you very much. Cheers.
