### ISSUE TITLE
Cannot compute size error when running script

### ISSUE THREAD

**Issue by mikemarbry** [monfresh/laptop#80]
Ran into an issue when running the `laptop` script where the installation of ruby fails due to a compute sizer error. I haven't been able to find anything that resolves the issue. 

At one point in time I was able to get homebrew to install successfully but on Rosetta. However I was only able to use the pre loaded ruby version that comes on all macs.

**Comment by monfresh** [comment]
Hi Mike. I'm sorry you're running into this issue. 

I'm pretty sure it's caused by the previous Rosetta installation. The good news is that I'm 99% sure how to fix it, and I'm working on a premium version of the script that will handle situations like yours. 

If you'd like to help me test it, you can be my first customer by [booking a $10 Zoom session with me](https://savvycal.com/monfresh/dev-setup) and we can try it out together.

That $10 will give you access to my private repo and lifetime access to the premium script.

**Comment by monfresh** [comment]
I'm gonna close this issue because I haven't heard back, and I'm also turning off issues in this repo. This repo will remain available, but without support. I'm only providing support for people who buy my premium script. If you're interested, shoot me an email.
